spring:
  application:
    name: springboot-cache
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/cache_db